AWSTemplateFormatVersion: '2010-09-09'
Description: 'EKS-configMap-customResource

  SAM Template for EKS-configMap-customResource

  '
Globals:
  Function:
    Timeout: 30
Outputs:
  MyFunction:
    Description: Lambda function Arn
    Value:
      Fn::GetAtt:
      - MyFunction
      - Arn
  MyFunctionIamRole:
    Description: Lambda function IAM role Arn
    Value:
      Fn::GetAtt:
      - MyFunctionRole
      - Arn
Resources:
  MyFunction:
    Properties:
      CodeUri: s3://eks-lambda-configmap-customresource/9ab49ec8a813c54f7720685f8175fb67
      Handler: main
      Policies:
      - AWSLambdaBasicExecutionRole
      - Statement:
        - Action:
          - eks:Describe*
          - eks:List*
          - eks:Update*
          Effect: Allow
          Resource: '*'
        Version: '2012-10-17'
      Runtime: go1.x
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
